### ISSUE TITLE
Routing in production build fails

### ISSUE THREAD

**Issue by cjmoeller** [maritimeconnectivity/ManagementPortal#100]
When building the portal for production with `npm run build:prod`, and using a http server to serve the portal, the user is redirected to https://example.com/pages/ir/organizations/...  after login, which returns a 404. This can be reproduced with the following Dockerfile:

```Dockerfile
# Stage 1: Build the Angular application in production mode
FROM node:14.20.1 AS production

WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install --save --legacy-deps

# Install the specific @types/ws package version
RUN npm install @types/ws@8.5.4

# Copy the rest of the application source code
COPY . .

# Build the Angular application with the production configuration
RUN npm run build:prod

# Stage 2: Create a production image
FROM nginx:alpine AS final

# Copy the built Angular app from the production stage to the final image
COPY --from=production /app/dist /usr/share/nginx/html

# Expose port 80 for serving the Angular app
EXPOSE 80

# Start the NGINX server
CMD ["nginx", "-g", "daemon off;"]


```

**Comment by JinkiJung** [comment]
Hi Julius,

I've made a commit (22364b6c9d086298be7d832b301425849bc2c1d3) for making this running without failure,

So the fix overwrites the default docker conf with nginx.conf added in the new commit during a build.

Mind that you need to be at the root of the project folder to run docker commands, as I clarified in the README.

Just let me know that works for you.  😊

Thank you for your input and trying this code to get dockerized.

**Comment by cjmoeller** [comment]
Thank you, works for me! :)

**Comment by cjmoeller** [comment]
Thank you, works for me! :)
