### ISSUE TITLE
Service Registry instance list not complete

### ISSUE THREAD

**Issue by nvasta** [maritimeconnectivity/ManagementPortal#125]
When looking into the MSR instance list we only get the top 20 results. All other results are skipped.

Even when searching, the portal does not seem to feed the query back to the MSR, rather it searches in the already loaded results.

We should be using the paging parameter in our instances query, to pick up the information for the page we are looking at in the portal.

**Comment by JinkiJung** [comment]
Thank you for reporting @nvasta! Just came back from a holiday week.

Paging in portal has been implemented for MIR, but not for MSR. It is not implemented yet.

In the implementation the total number of pages 'totalPages' is fetched from the initial query which is possible for MIR GET API, i.e., https://test-api.maritimeconnectivity.net/swagger-ui/index.html#/service-controller/getOrganizationServices

Then the number of pages with a proper link can be created, which is not possible for MSR GET. 

Calling multiple queries to infer 'totalPages' would be the best option in MSR? or would it be possible to make the paging work as MIR doing?

**Comment by nvasta** [comment]
In the MSR, I followed the method from the old approach, where the number of total pages was added as a header (weird right?). So you will find the total number in the header "X-Total-Count".

Overall, I tried to keep as much of the functionality similar in case there were other dependent services (at least at the time).

There is another POST interface that can be used directly for [jQuery Datatables](https://datatables.net/):
- /api/instances/dt
Probably you wouldn't want to use that, but let me know if you do.

**Comment by JinkiJung** [comment]
Thank you for the explanation, Nikos! 

Instead of using a header I've made a fix with a call for Datatables as recommended. 

Now it works like a charm in paging, from tests on my end.

Please take a look this branch - [fix-issue125-instance-list](https://github.com/maritimeconnectivity/ManagementPortal/tree/fix-issue125-instance-list) - and shout out if something goes wrong. :)

I will merge this one to the main at the end of next week.

**Comment by nvasta** [comment]
Nice!!!
